[advisories]
ignore = [
  "RUSTSEC-2024-0436",
  "RUSTSEC-2025-0134",
]

[licenses]
allow = [
  "MIT",
  "GPL-3.0-only",
  "Apache-2.0",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "OpenSSL",
  "Unicode-3.0",
  "ISC",
  "Zlib",
  "LicenseRef-hdf5",
  "BSL-1.0",
  "CC0-1.0",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
  { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "hdf5-metno-src"
expression = "LicenseRef-hdf5"
license-files = [
  { path = "ext/hdf5/COPYING", hash = 0xf13e3591 },
]

[bans]
multiple-versions = "allow"
